### ISSUE TITLE
⏰ Base Queue Functionality

### ISSUE THREAD

**Issue by emilyab3** [BraeWebb/special#1]
### Description
get le queue up and runnin

### Milestones
- [x] Allow user to join queue
- [x] Allow user to leave queue (or be removed from the queue)
- [x] Display users in the queue
- [x] Have both a quick question and long question queue
- [x] Display relevant details (such as number of questions asked and amount of time waited)
