### ISSUE TITLE
📈 Statistics Tracking

### ISSUE THREAD

**Issue by emilyab3** [BraeWebb/special#2]
### Description
some fancy statisticy bois on queue usage

### Milestones
- [ ] Collect usage data
- [ ] Store usage data
- [ ] Allow charts and graphs to be generated
