### ISSUE TITLE
🏢 Report Management

### ISSUE THREAD

**Issue by BraeWebb** [BraeWebb/special#37]
Manage MoSS reports digitally by assigning users roles and having annotated reports.

Requirements
- [x] #34 Download the report data from a generated URL
- [x] #35 Render the report
- [x] #36 List all the reports that a user has been assigned a role with
- [x] #38 Configure reports and report permission
