### ISSUE TITLE
🥇 Queue Priorities

### ISSUE THREAD

**Issue by emilyab3** [BraeWebb/special#4]
### Description
order people in the queue based on various properties

### Milestones
- [ ] Short vs long queue
- [ ] Signed onto the current contact vs not
- [ ] Wait times
- [ ] Number of questions already asked
