### ISSUE TITLE
📅 Base Allocation Functionality

### ISSUE THREAD

**Issue by emilyab3** [BraeWebb/special#6]
### Description
The MVP features of the allocation tool

### Milestones
- [x] Process CSV files of staff availability and contact hour details
- [x] Take into account basic staff preferences (such as min/max number of hours)
- [x] Ability to detect clashes between concurrent classes and avoid double-allocations of staff
