### ISSUE TITLE
🛄 Add a Database to the Queue

### ISSUE THREAD

**Issue by emilyab3** [BraeWebb/special#9]
### Description
Integrates the queue with a back-end to store details of users and their queue activity

### Milestones
- [x] Add users to the database when they join the queue
- [ ] Increment question count when a user joins
- [ ] Handle count for users leaving the queue
- [x] Only display users who have unanswered questions
- [ ] Separate data for quick and long questions
- [x] Have relevant details be dynamically updated based on database
